name: self_service_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animate_do: ^3.3.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  lottie: ^3.1.0
  page_transition: ^2.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "wssteak_logo"
  ios: true
  image_path: "assets/wssteak_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
